/**************************************************************************************** 
*		Project Name		:	ILT														*				       
*		File Name			:   rowcursor.cpp											*					   
*		Author				:	Chaman Lal Sharma										*		                          
*		Date				:	25th May.2011											*			                      
*		Version of file		:	V1.00													*			                      
****************************************************************************************/

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rowcursor.h"


/////////////////////////////////////////////////////////////////////////////
// CRowCursor properties

/////////////////////////////////////////////////////////////////////////////
// CRowCursor operations
