/************************************************************************************************
*		Project Name		:	ILT																*
*		File Name			:	rowcursor.h			    									    *
*		Author				:	Chaman Lal Sharma												*
*		Date				:	25th May 2011													*
*		Version of file		:	V1.00															*
*		Description 		:	This File includes the declarations of the following:-          *
*																								*
*								public member functions:-                                       *
*									CRowCursor()												*
*									CRowCursor(LPDISPATCH pDispatch) :							*
*										COleDispatchDriver(pDispatch) {}						*
*									CRowCursor(const CRowCursor& dispatchSrc) :					*
*										COleDispatchDriver(dispatchSrc)							*
************************************************************************************************/

#if !defined(AFX_ROWCURSOR_H__F6CC18B5_AE30_46BB_A372_409C4A11F0A8__INCLUDED_)
#define AFX_ROWCURSOR_H__F6CC18B5_AE30_46BB_A372_409C4A11F0A8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRowCursor wrapper class

class CRowCursor : public COleDispatchDriver
{
public:
	CRowCursor() {}		// Calls COleDispatchDriver default constructor
	CRowCursor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRowCursor(const CRowCursor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ROWCURSOR_H__F6CC18B5_AE30_46BB_A372_409C4A11F0A8__INCLUDED_)
