#ifndef _SIPU_AMSTRUCT_H
#define _SIPU_AMSTRUCT_H


#include <afxmt.h>
#include "SIPU_SDU_GndRig.h"
#include "DataStruct.h"
#include "Macros.h"
#include <Math.h>


/* Auto Mode channel Macros */
#define IT_SIPU_MARINC_CHAN1		1
#define IT_SIPU_MARINC_CHAN2		3
#define IT_SIPU_MARINC_CHAN3		5
#define IT_SIPU_MARINC_CHAN4		7
#define IT_SIPU_EARINC_CHAN1		2
#define IT_SIPU_EARINC_CHAN2		4
#define IT_SIPU_EARINC_CHAN3		6
#define IT_SIPU_EARINC_CHAN4		8
#define IT_SIPU_FCHAN_N1			2
#define IT_SIPU_FCHAN_N2			1
#define IT_SIPU_ARCHAN_EEU			3
#define IT_SIPU_FCHAN_FUELFLOW		3
#define IT_SIPU_FCHAN_LHWING		3
#define IT_SIPU_FCHAN_RHWING		4
#define IT_SIPU_ACHAN_MHYDPRES		1
#define IT_SIPU_ACHAN_EHYDPRES		2
#define IT_SIPU_ACHAN_LHBRKPRES		3
#define IT_SIPU_ACHAN_RHBRKPRES		4
#define IT_SIPU_ACHAN_MBRKPRES		5
#define IT_SIPU_ACHAN_TP			3
#define IT_SIPU_ACHAN_AIL			12
#define IT_SIPU_ACHAN_FLAP			4
#define IT_SIPU_ACHAN_RUDDER		13
#define IT_SIPU_ACHAN_DCBUS1		14
#define IT_SIPU_ACHAN_DCBUS2		15

/* ARINC output MSBs */
#define IT_TP_LSB							0.0625f
#define IT_RUD_LSB							0.0625f
#define IT_AIL_LSB							0.0625f
#define IT_FLAP_LSB							0.0625f
#define IT_EGT_LSB							0.5f
#define IT_HYD_MAIN_LSB						0.25f
#define IT_HYD_EMER_LSB						0.25f
#define IT_LH_BRK_LSB						0.25f
#define IT_RH_BRK_LSB						0.25f
#define IT_MAIN_BRK_LSB						0.25f
#define	IT_DC1_LSB							0.0625f
#define IT_DC2_LSB							0.0625f
#define IT_N1_LSB							0.0625f
#define IT_N2_LSB							0.0625f
#define IT_EEU_N1_LSB					0.000488f
#define IT_EEU_N2_LSB					0.000488f
#define IT_EEU_EGT_LSB					0.003906f
#define IT_RH_WING_FREQ_LSB				8
#define IT_LH_WING_FREQ_LSB				8
#define IT_FUSELAGE_FREQ_LSB			8
#define IT_TOT_INT_FUEL_LSB				0.5f
#define IT_FUEL_TRAN_LSB					0.0f
#define IT_CABIN_DIFF_LSB					0.5f
#define IT_AHRS_STATUS_LSB					0.0f
#define IT_ARINC_BNR						1
#define IT_FIND_MSB							131072
#define IT_ARINC429_DATA_BITS			18

/* Multiplication factor */
#define IT_TP_MUL			2.0f
#define IT_AILERON_MUL		1.0f
#define IT_FLAP_MUL			2.0f
#define IT_RUDDER_MUL			1.0f
#define IT_DC1_MUL			4.012f
#define IT_DC2_MUL			4.012f

/* To be add later all the max and min values */
#define IT_SIPU_EGTMAXVAL	5	
#define IT_SIPU_EGTMINVAL	3

#define IT_SIPU_EEUMAXVAL	5
#define IT_SIPU_EEUMINVAL	3

#define IT_SIPU_N1FREQMAXVAL	5
#define IT_SIPU_N1FREQMINVAL	3

#define IT_SIPU_N2FREQMAXVAL	5
#define IT_SIPU_N2FREQMINVAL	3

#define IT_SIPU_FUSELAGEMAXVAL	9.925f
#define IT_SIPU_FUSELAGEMINVAL	5.08f

#define IT_SIPU_FTLHWTMAXVAL	5
#define IT_SIPU_FTLHWTMINVAL	3

#define IT_SIPU_FTRHWTMAXVAL	5.3f
#define IT_SIPU_FTRHWTMINVAL	3.3f

#define IT_SIPU_FTLHDTMAXVAL	5.3f
#define IT_SIPU_FTLHDTMINVAL	3.3f

#define IT_SIPU_FTRHDTMAXVAL	5.3f
#define IT_SIPU_FTRHDTMINVAL	3.3f

#define IT_SIPU_MHYDPRES_MAXVAL		5.3f
#define IT_SIPU_MHYDPRES_MINVAL		3.3f

#define IT_SIPU_EHYDPRES_MAXVAL		5.3f
#define IT_SIPU_EHYDPRES_MINVAL		3.3f

#define IT_SIPU_LHBRKPRES_MAXVAL	5.3f
#define IT_SIPU_LHBRKPRES_MINVAL	3.3f

#define IT_SIPU_RHBRKPRES_MAXVAL	5.3f
#define IT_SIPU_RHBRKPRES_MINVAL	3.3f

#define IT_SIPU_MSUPBRKPRES_MAXVAL	5.3f
#define IT_SIPU_MSUPBRKPRES_MINVAL	3.3f

#define IT_SIPU_TPTRIMPOS_MAXVAL	5.3f
#define IT_SIPU_TPTRIMPOS_MINVAL	3.3f

#define IT_SIPU_AILTRIMPOS_MAXVAL	5.3f
#define IT_SIPU_AILTRIMPOS_MINVAL	3.3f

#define IT_SIPU_RUDTRIMPOS_MAXVAL	5.3f
#define IT_SIPU_RUDTRIMPOS_MINVAL	3.3f

#define IT_SIPU_FLAPPOS_MAXVAL		5.3f
#define IT_SIPU_FLAPPOS_MINVAL		3.3f

#define IT_SIPU_DCBUS1_MAXVAL		5.3f
#define IT_SIPU_DCBUS1_MINVAL		3.3f

#define IT_SIPU_DCBUS2_MAXVAL		5.3f
#define IT_SIPU_DCBUS2_MINVAL		3.3f

#define IT_SIPU_CABPRES_MAXVAL		5.3f
#define IT_SIPU_CABPRES_MINVAL		3.3f

#define IT_SIPU_AHRS_MAXVAL			5.3f
#define IT_SIPU_AHRS_MINVAL			3.3f

#define IT_SIPU_FFLOW_MAXVAL		5.3f
#define IT_SIPU_FFLOW_MINVAL		3.3f

#define IT_SIPU_FTEMP_MAXVAL		5.3f
#define IT_SIPU_FTEMP_MINVAL		3.3f

#define EGT_VALUE1	IT_SIPU_EGTMINVAL+((IT_SIPU_EGTMAXVAL-IT_SIPU_EGTMINVAL)*NFIVE_PERCENT)
#define EGT_VALUE2	IT_SIPU_EGTMINVAL+((IT_SIPU_EGTMAXVAL-IT_SIPU_EGTMINVAL)*ZERO_PERCENT)
#define EGT_VALUE3	IT_SIPU_EGTMINVAL+((IT_SIPU_EGTMAXVAL-IT_SIPU_EGTMINVAL)*FIFTY_PERCENT)
#define EGT_VALUE4	IT_SIPU_EGTMINVAL+((IT_SIPU_EGTMAXVAL-IT_SIPU_EGTMINVAL)*HUNDRED_PERCENT)
#define EGT_VALUE5	IT_SIPU_EGTMINVAL+((IT_SIPU_EGTMAXVAL-IT_SIPU_EGTMINVAL)*HUNDRED_FIVE_PERCENT)

#define EEU_VALUE1	IT_SIPU_EEUMINVAL+((IT_SIPU_EEUMAXVAL-IT_SIPU_EEUMINVAL)*NFIVE_PERCENT)
#define EEU_VALUE2	IT_SIPU_EEUMINVAL+((IT_SIPU_EEUMAXVAL-IT_SIPU_EEUMINVAL)*ZERO_PERCENT)
#define EEU_VALUE3	IT_SIPU_EEUMINVAL+((IT_SIPU_EEUMAXVAL-IT_SIPU_EEUMINVAL)*FIFTY_PERCENT)
#define EEU_VALUE4	IT_SIPU_EEUMINVAL+((IT_SIPU_EEUMAXVAL-IT_SIPU_EEUMINVAL)*HUNDRED_PERCENT)
#define EEU_VALUE5	IT_SIPU_EEUMINVAL+((IT_SIPU_EEUMAXVAL-IT_SIPU_EEUMINVAL)*HUNDRED_FIVE_PERCENT)

#define N1FREQ_VALUE1	IT_SIPU_N1FREQMINVAL+((IT_SIPU_N1FREQMAXVAL-IT_SIPU_N1FREQMINVAL)*NFIVE_PERCENT)
#define N1FREQ_VALUE2	IT_SIPU_N1FREQMINVAL+((IT_SIPU_N1FREQMAXVAL-IT_SIPU_N1FREQMINVAL)*ZERO_PERCENT)
#define N1FREQ_VALUE3	IT_SIPU_N1FREQMINVAL+((IT_SIPU_N1FREQMAXVAL-IT_SIPU_N1FREQMINVAL)*FIFTY_PERCENT)
#define N1FREQ_VALUE4	IT_SIPU_N1FREQMINVAL+((IT_SIPU_N1FREQMAXVAL-IT_SIPU_N1FREQMINVAL)*HUNDRED_PERCENT)
#define N1FREQ_VALUE5	IT_SIPU_N1FREQMINVAL+((IT_SIPU_N1FREQMAXVAL-IT_SIPU_N1FREQMINVAL)*HUNDRED_FIVE_PERCENT)

#define N2FREQ_VALUE1	IT_SIPU_N2FREQMINVAL+((IT_SIPU_N2FREQMAXVAL-IT_SIPU_N2FREQMINVAL)*NFIVE_PERCENT)
#define N2FREQ_VALUE2	IT_SIPU_N2FREQMINVAL+((IT_SIPU_N2FREQMAXVAL-IT_SIPU_N2FREQMINVAL)*ZERO_PERCENT)
#define N2FREQ_VALUE3	IT_SIPU_N2FREQMINVAL+((IT_SIPU_N2FREQMAXVAL-IT_SIPU_N2FREQMINVAL)*FIFTY_PERCENT)
#define N2FREQ_VALUE4	IT_SIPU_N2FREQMINVAL+((IT_SIPU_N2FREQMAXVAL-IT_SIPU_N2FREQMINVAL)*HUNDRED_PERCENT)
#define N2FREQ_VALUE5	IT_SIPU_N2FREQMINVAL+((IT_SIPU_N2FREQMAXVAL-IT_SIPU_N2FREQMINVAL)*HUNDRED_FIVE_PERCENT)

#define FUSELAGE_VALUE1	IT_SIPU_FUSELAGEMINVAL+((IT_SIPU_FUSELAGEMAXVAL-IT_SIPU_FUSELAGEMINVAL)*NFIVE_PERCENT)
#define FUSELAGE_VALUE2	IT_SIPU_FUSELAGEMINVAL+((IT_SIPU_FUSELAGEMAXVAL-IT_SIPU_FUSELAGEMINVAL)*ZERO_PERCENT)
#define FUSELAGE_VALUE3	IT_SIPU_FUSELAGEMINVAL+((IT_SIPU_FUSELAGEMAXVAL-IT_SIPU_FUSELAGEMINVAL)*FIFTY_PERCENT)
#define FUSELAGE_VALUE4	IT_SIPU_FUSELAGEMINVAL+((IT_SIPU_FUSELAGEMAXVAL-IT_SIPU_FUSELAGEMINVAL)*HUNDRED_PERCENT)
#define FUSELAGE_VALUE5	IT_SIPU_FUSELAGEMINVAL+((IT_SIPU_FUSELAGEMAXVAL-IT_SIPU_FUSELAGEMINVAL)*HUNDRED_FIVE_PERCENT)

#define FTLHWT_VALUE1	IT_SIPU_FTLHWTMINVAL+((IT_SIPU_FTLHWTMAXVAL-IT_SIPU_FTLHWTMINVAL)*NFIVE_PERCENT)
#define FTLHWT_VALUE2	IT_SIPU_FTLHWTMINVAL+((IT_SIPU_FTLHWTMAXVAL-IT_SIPU_FTLHWTMINVAL)*ZERO_PERCENT)
#define FTLHWT_VALUE3	IT_SIPU_FTLHWTMINVAL+((IT_SIPU_FTLHWTMAXVAL-IT_SIPU_FTLHWTMINVAL)*FIFTY_PERCENT)
#define FTLHWT_VALUE4	IT_SIPU_FTLHWTMINVAL+((IT_SIPU_FTLHWTMAXVAL-IT_SIPU_FTLHWTMINVAL)*HUNDRED_PERCENT)
#define FTLHWT_VALUE5	IT_SIPU_FTLHWTMINVAL+((IT_SIPU_FTLHWTMAXVAL-IT_SIPU_FTLHWTMINVAL)*HUNDRED_FIVE_PERCENT)

#define FTRHWT_VALUE1	IT_SIPU_FTRHWTMINVAL+((IT_SIPU_FTRHWTMAXVAL-IT_SIPU_FTRHWTMINVAL)*NFIVE_PERCENT)
#define FTRHWT_VALUE2	IT_SIPU_FTRHWTMINVAL+((IT_SIPU_FTRHWTMAXVAL-IT_SIPU_FTRHWTMINVAL)*ZERO_PERCENT)
#define FTRHWT_VALUE3	IT_SIPU_FTRHWTMINVAL+((IT_SIPU_FTRHWTMAXVAL-IT_SIPU_FTRHWTMINVAL)*FIFTY_PERCENT)
#define FTRHWT_VALUE4	IT_SIPU_FTRHWTMINVAL+((IT_SIPU_FTRHWTMAXVAL-IT_SIPU_FTRHWTMINVAL)*HUNDRED_PERCENT)
#define FTRHWT_VALUE5	IT_SIPU_FTRHWTMINVAL+((IT_SIPU_FTRHWTMAXVAL-IT_SIPU_FTRHWTMINVAL)*HUNDRED_FIVE_PERCENT)

#define FTLHDT_VALUE1	IT_SIPU_FTLHDTMINVAL+((IT_SIPU_FTLHDTMAXVAL-IT_SIPU_FTLHDTMINVAL)*NFIVE_PERCENT)
#define FTLHDT_VALUE2	IT_SIPU_FTLHDTMINVAL+((IT_SIPU_FTLHDTMAXVAL-IT_SIPU_FTLHDTMINVAL)*ZERO_PERCENT)
#define FTLHDT_VALUE3	IT_SIPU_FTLHDTMINVAL+((IT_SIPU_FTLHDTMAXVAL-IT_SIPU_FTLHDTMINVAL)*FIFTY_PERCENT)
#define FTLHDT_VALUE4	IT_SIPU_FTLHDTMINVAL+((IT_SIPU_FTLHDTMAXVAL-IT_SIPU_FTLHDTMINVAL)*HUNDRED_PERCENT)
#define FTLHDT_VALUE5	IT_SIPU_FTLHDTMINVAL+((IT_SIPU_FTLHDTMAXVAL-IT_SIPU_FTLHDTMINVAL)*HUNDRED_FIVE_PERCENT)

#define FTRHDT_VALUE1	IT_SIPU_FTRHDTMINVAL+((IT_SIPU_FTRHDTMAXVAL-IT_SIPU_FTRHDTMINVAL)*NFIVE_PERCENT)
#define FTRHDT_VALUE2	IT_SIPU_FTRHDTMINVAL+((IT_SIPU_FTRHDTMAXVAL-IT_SIPU_FTRHDTMINVAL)*ZERO_PERCENT)
#define FTRHDT_VALUE3	IT_SIPU_FTRHDTMINVAL+((IT_SIPU_FTRHDTMAXVAL-IT_SIPU_FTRHDTMINVAL)*FIFTY_PERCENT)
#define FTRHDT_VALUE4	IT_SIPU_FTRHDTMINVAL+((IT_SIPU_FTRHDTMAXVAL-IT_SIPU_FTRHDTMINVAL)*HUNDRED_PERCENT)
#define FTRHDT_VALUE5	IT_SIPU_FTRHDTMINVAL+((IT_SIPU_FTRHDTMAXVAL-IT_SIPU_FTRHDTMINVAL)*HUNDRED_FIVE_PERCENT)

#define DISCRETE_1		0
#define DISCRETE_2		1
#define DISCRETE_3		2
#define DISCRETE_4		3
#define DISCRETE_5		4
#define DISCRETE_6		5
#define DISCRETE_7		6
#define DISCRETE_8		8

#define MHYDPRES_VALUE1		IT_SIPU_MHYDPRES_MINVAL+((IT_SIPU_MHYDPRES_MAXVAL-IT_SIPU_MHYDPRES_MINVAL)*NFIVE_PERCENT)
#define MHYDPRES_VALUE2		IT_SIPU_MHYDPRES_MINVAL+((IT_SIPU_MHYDPRES_MAXVAL-IT_SIPU_MHYDPRES_MINVAL)*ZERO_PERCENT)
#define MHYDPRES_VALUE3		IT_SIPU_MHYDPRES_MINVAL+((IT_SIPU_MHYDPRES_MAXVAL-IT_SIPU_MHYDPRES_MINVAL)*FIFTY_PERCENT)
#define MHYDPRES_VALUE4		IT_SIPU_MHYDPRES_MINVAL+((IT_SIPU_MHYDPRES_MAXVAL-IT_SIPU_MHYDPRES_MINVAL)*HUNDRED_PERCENT)
#define MHYDPRES_VALUE5		IT_SIPU_MHYDPRES_MINVAL+((IT_SIPU_MHYDPRES_MAXVAL-IT_SIPU_MHYDPRES_MINVAL)*HUNDRED_FIVE_PERCENT)

#define EHYDPRES_VALUE1		IT_SIPU_EHYDPRES_MINVAL+((IT_SIPU_EHYDPRES_MAXVAL-IT_SIPU_EHYDPRES_MINVAL)*NFIVE_PERCENT)
#define EHYDPRES_VALUE2		IT_SIPU_EHYDPRES_MINVAL+((IT_SIPU_EHYDPRES_MAXVAL-IT_SIPU_EHYDPRES_MINVAL)*ZERO_PERCENT)
#define EHYDPRES_VALUE3		IT_SIPU_EHYDPRES_MINVAL+((IT_SIPU_EHYDPRES_MAXVAL-IT_SIPU_EHYDPRES_MINVAL)*FIFTY_PERCENT)
#define EHYDPRES_VALUE4		IT_SIPU_EHYDPRES_MINVAL+((IT_SIPU_EHYDPRES_MAXVAL-IT_SIPU_EHYDPRES_MINVAL)*HUNDRED_PERCENT)
#define EHYDPRES_VALUE5		IT_SIPU_EHYDPRES_MINVAL+((IT_SIPU_EHYDPRES_MAXVAL-IT_SIPU_EHYDPRES_MINVAL)*HUNDRED_FIVE_PERCENT)

#define LHBRKPRES_VALUE1	IT_SIPU_LHBRKPRES_MINVAL+((IT_SIPU_LHBRKPRES_MAXVAL-IT_SIPU_LHBRKPRES_MINVAL)*NFIVE_PERCENT)
#define LHBRKPRES_VALUE2	IT_SIPU_LHBRKPRES_MINVAL+((IT_SIPU_LHBRKPRES_MAXVAL-IT_SIPU_LHBRKPRES_MINVAL)*ZERO_PERCENT)
#define LHBRKPRES_VALUE3	IT_SIPU_LHBRKPRES_MINVAL+((IT_SIPU_LHBRKPRES_MAXVAL-IT_SIPU_LHBRKPRES_MINVAL)*FIFTY_PERCENT)
#define LHBRKPRES_VALUE4	IT_SIPU_LHBRKPRES_MINVAL+((IT_SIPU_LHBRKPRES_MAXVAL-IT_SIPU_LHBRKPRES_MINVAL)*HUNDRED_PERCENT)
#define LHBRKPRES_VALUE5	IT_SIPU_LHBRKPRES_MINVAL+((IT_SIPU_LHBRKPRES_MAXVAL-IT_SIPU_LHBRKPRES_MINVAL)*HUNDRED_FIVE_PERCENT)

#define RHBRKPRES_VALUE1	IT_SIPU_RHBRKPRES_MINVAL+((IT_SIPU_RHBRKPRES_MAXVAL-IT_SIPU_RHBRKPRES_MINVAL)*NFIVE_PERCENT)
#define RHBRKPRES_VALUE2	IT_SIPU_RHBRKPRES_MINVAL+((IT_SIPU_RHBRKPRES_MAXVAL-IT_SIPU_RHBRKPRES_MINVAL)*ZERO_PERCENT)
#define RHBRKPRES_VALUE3	IT_SIPU_RHBRKPRES_MINVAL+((IT_SIPU_RHBRKPRES_MAXVAL-IT_SIPU_RHBRKPRES_MINVAL)*FIFTY_PERCENT)
#define RHBRKPRES_VALUE4	IT_SIPU_RHBRKPRES_MINVAL+((IT_SIPU_RHBRKPRES_MAXVAL-IT_SIPU_RHBRKPRES_MINVAL)*HUNDRED_PERCENT)
#define RHBRKPRES_VALUE5	IT_SIPU_RHBRKPRES_MINVAL+((IT_SIPU_RHBRKPRES_MAXVAL-IT_SIPU_RHBRKPRES_MINVAL)*HUNDRED_FIVE_PERCENT)

#define MSUPBRKPRES_VALUE1		IT_SIPU_MSUPBRKPRES_MINVAL+((IT_SIPU_MSUPBRKPRES_MAXVAL-IT_SIPU_MSUPBRKPRES_MINVAL)*NFIVE_PERCENT)
#define MSUPBRKPRES_VALUE2		IT_SIPU_MSUPBRKPRES_MINVAL+((IT_SIPU_MSUPBRKPRES_MAXVAL-IT_SIPU_MSUPBRKPRES_MINVAL)*ZERO_PERCENT)
#define MSUPBRKPRES_VALUE3		IT_SIPU_MSUPBRKPRES_MINVAL+((IT_SIPU_MSUPBRKPRES_MAXVAL-IT_SIPU_MSUPBRKPRES_MINVAL)*FIFTY_PERCENT)
#define MSUPBRKPRES_VALUE4		IT_SIPU_MSUPBRKPRES_MINVAL+((IT_SIPU_MSUPBRKPRES_MAXVAL-IT_SIPU_MSUPBRKPRES_MINVAL)*HUNDRED_PERCENT)
#define MSUPBRKPRES_VALUE5		IT_SIPU_MSUPBRKPRES_MINVAL+((IT_SIPU_MSUPBRKPRES_MAXVAL-IT_SIPU_MSUPBRKPRES_MINVAL)*HUNDRED_FIVE_PERCENT)

#define TPTRIMPOS_VALUE1		(IT_SIPU_TPTRIMPOS_MAXVAL-IT_SIPU_TPTRIMPOS_MINVAL)*NFIVE_PERCENT
#define TPTRIMPOS_VALUE2		(IT_SIPU_TPTRIMPOS_MAXVAL-IT_SIPU_TPTRIMPOS_MINVAL)*ZERO_PERCENT
#define TPTRIMPOS_VALUE3		(IT_SIPU_TPTRIMPOS_MAXVAL-IT_SIPU_TPTRIMPOS_MINVAL)*FIFTY_PERCENT
#define TPTRIMPOS_VALUE4		(IT_SIPU_TPTRIMPOS_MAXVAL-IT_SIPU_TPTRIMPOS_MINVAL)*HUNDRED_PERCENT
#define TPTRIMPOS_VALUE5		(IT_SIPU_TPTRIMPOS_MAXVAL-IT_SIPU_TPTRIMPOS_MINVAL)*HUNDRED_FIVE_PERCENT

#define AILTRIMPOS_VALUE1		(IT_SIPU_AILTRIMPOS_MAXVAL-IT_SIPU_AILTRIMPOS_MINVAL)*NFIVE_PERCENT
#define AILTRIMPOS_VALUE2		(IT_SIPU_AILTRIMPOS_MAXVAL-IT_SIPU_AILTRIMPOS_MINVAL)*ZERO_PERCENT
#define AILTRIMPOS_VALUE3		(IT_SIPU_AILTRIMPOS_MAXVAL-IT_SIPU_AILTRIMPOS_MINVAL)*FIFTY_PERCENT
#define AILTRIMPOS_VALUE4		(IT_SIPU_AILTRIMPOS_MAXVAL-IT_SIPU_AILTRIMPOS_MINVAL)*HUNDRED_PERCENT
#define AILTRIMPOS_VALUE5		(IT_SIPU_AILTRIMPOS_MAXVAL-IT_SIPU_AILTRIMPOS_MINVAL)*HUNDRED_FIVE_PERCENT

#define RUDTRIMPOS_VALUE1		(IT_SIPU_RUDTRIMPOS_MAXVAL-IT_SIPU_RUDTRIMPOS_MINVAL)*NFIVE_PERCENT
#define RUDTRIMPOS_VALUE2		(IT_SIPU_RUDTRIMPOS_MAXVAL-IT_SIPU_RUDTRIMPOS_MINVAL)*ZERO_PERCENT
#define RUDTRIMPOS_VALUE3		(IT_SIPU_RUDTRIMPOS_MAXVAL-IT_SIPU_RUDTRIMPOS_MINVAL)*FIFTY_PERCENT
#define RUDTRIMPOS_VALUE4		(IT_SIPU_RUDTRIMPOS_MAXVAL-IT_SIPU_RUDTRIMPOS_MINVAL)*HUNDRED_PERCENT
#define RUDTRIMPOS_VALUE5		(IT_SIPU_RUDTRIMPOS_MAXVAL-IT_SIPU_RUDTRIMPOS_MINVAL)*HUNDRED_FIVE_PERCENT

#define FLAPPOS_VALUE1		(IT_SIPU_FLAPPOS_MAXVAL-IT_SIPU_FLAPPOS_MINVAL)*NFIVE_PERCENT
#define FLAPPOS_VALUE2		(IT_SIPU_FLAPPOS_MAXVAL-IT_SIPU_FLAPPOS_MINVAL)*ZERO_PERCENT
#define FLAPPOS_VALUE3		(IT_SIPU_FLAPPOS_MAXVAL-IT_SIPU_FLAPPOS_MINVAL)*FIFTY_PERCENT
#define FLAPPOS_VALUE4		(IT_SIPU_FLAPPOS_MAXVAL-IT_SIPU_FLAPPOS_MINVAL)*HUNDRED_PERCENT
#define FLAPPOS_VALUE5		(IT_SIPU_FLAPPOS_MAXVAL-IT_SIPU_FLAPPOS_MINVAL)*HUNDRED_FIVE_PERCENT

#define DCBUS1_VALUE1		(IT_SIPU_DCBUS1_MAXVAL-IT_SIPU_DCBUS1_MINVAL)*NFIVE_PERCENT
#define DCBUS1_VALUE2		(IT_SIPU_DCBUS1_MAXVAL-IT_SIPU_DCBUS1_MINVAL)*ZERO_PERCENT
#define DCBUS1_VALUE3		(IT_SIPU_DCBUS1_MAXVAL-IT_SIPU_DCBUS1_MINVAL)*FIFTY_PERCENT
#define DCBUS1_VALUE4		(IT_SIPU_DCBUS1_MAXVAL-IT_SIPU_DCBUS1_MINVAL)*HUNDRED_PERCENT
#define DCBUS1_VALUE5		(IT_SIPU_DCBUS1_MAXVAL-IT_SIPU_DCBUS1_MINVAL)*HUNDRED_FIVE_PERCENT

#define DCBUS2_VALUE1		(IT_SIPU_DCBUS2_MAXVAL-IT_SIPU_DCBUS2_MINVAL)*NFIVE_PERCENT
#define DCBUS2_VALUE2		(IT_SIPU_DCBUS2_MAXVAL-IT_SIPU_DCBUS2_MINVAL)*ZERO_PERCENT
#define DCBUS2_VALUE3		(IT_SIPU_DCBUS2_MAXVAL-IT_SIPU_DCBUS2_MINVAL)*FIFTY_PERCENT
#define DCBUS2_VALUE4		(IT_SIPU_DCBUS2_MAXVAL-IT_SIPU_DCBUS2_MINVAL)*HUNDRED_PERCENT
#define DCBUS2_VALUE5		(IT_SIPU_DCBUS2_MAXVAL-IT_SIPU_DCBUS2_MINVAL)*HUNDRED_FIVE_PERCENT

#define CABPRES_VALUE1		(IT_SIPU_CABPRES_MAXVAL-IT_SIPU_CABPRES_MINVAL)*NFIVE_PERCENT
#define CABPRES_VALUE2		(IT_SIPU_CABPRES_MAXVAL-IT_SIPU_CABPRES_MINVAL)*ZERO_PERCENT
#define CABPRES_VALUE3		(IT_SIPU_CABPRES_MAXVAL-IT_SIPU_CABPRES_MINVAL)*FIFTY_PERCENT
#define CABPRES_VALUE4		(IT_SIPU_CABPRES_MAXVAL-IT_SIPU_CABPRES_MINVAL)*HUNDRED_PERCENT
#define CABPRES_VALUE5		(IT_SIPU_CABPRES_MAXVAL-IT_SIPU_CABPRES_MINVAL)*HUNDRED_FIVE_PERCENT

#define AHRS_VALUE1			(IT_SIPU_AHRS_MAXVAL-IT_SIPU_AHRS_MINVAL)*NFIVE_PERCENT
#define AHRS_VALUE2			(IT_SIPU_AHRS_MAXVAL-IT_SIPU_AHRS_MINVAL)*ZERO_PERCENT
#define AHRS_VALUE3			(IT_SIPU_AHRS_MAXVAL-IT_SIPU_AHRS_MINVAL)*FIFTY_PERCENT
#define AHRS_VALUE4			(IT_SIPU_AHRS_MAXVAL-IT_SIPU_AHRS_MINVAL)*HUNDRED_PERCENT
#define AHRS_VALUE5			(IT_SIPU_AHRS_MAXVAL-IT_SIPU_AHRS_MINVAL)*HUNDRED_FIVE_PERCENT

#define FUELFLOW_VALUE1		IT_SIPU_FFLOW_MINVAL+((IT_SIPU_FFLOW_MAXVAL-IT_SIPU_FFLOW_MINVAL)*NFIVE_PERCENT)
#define FUELFLOW_VALUE2		IT_SIPU_FFLOW_MINVAL+((IT_SIPU_FFLOW_MAXVAL-IT_SIPU_FFLOW_MINVAL)*ZERO_PERCENT)
#define FUELFLOW_VALUE3		IT_SIPU_FFLOW_MINVAL+((IT_SIPU_FFLOW_MAXVAL-IT_SIPU_FFLOW_MINVAL)*FIFTY_PERCENT)
#define FUELFLOW_VALUE4		IT_SIPU_FFLOW_MINVAL+((IT_SIPU_FFLOW_MAXVAL-IT_SIPU_FFLOW_MINVAL)*HUNDRED_PERCENT)
#define FUELFLOW_VALUE5		IT_SIPU_FFLOW_MINVAL+((IT_SIPU_FFLOW_MAXVAL-IT_SIPU_FFLOW_MINVAL)*HUNDRED_FIVE_PERCENT)

#define FUELTEMP_VALUE1		IT_SIPU_FTEMP_MINVAL+((IT_SIPU_FTEMP_MAXVAL-IT_SIPU_FTEMP_MINVAL)*NFIVE_PERCENT)
#define FUELTEMP_VALUE2		IT_SIPU_FTEMP_MINVAL+((IT_SIPU_FTEMP_MAXVAL-IT_SIPU_FTEMP_MINVAL)*ZERO_PERCENT)
#define FUELTEMP_VALUE3		IT_SIPU_FTEMP_MINVAL+((IT_SIPU_FTEMP_MAXVAL-IT_SIPU_FTEMP_MINVAL)*FIFTY_PERCENT)
#define FUELTEMP_VALUE4		IT_SIPU_FTEMP_MINVAL+((IT_SIPU_FTEMP_MAXVAL-IT_SIPU_FTEMP_MINVAL)*HUNDRED_PERCENT)
#define FUELTEMP_VALUE5		IT_SIPU_FTEMP_MINVAL+((IT_SIPU_FTEMP_MAXVAL-IT_SIPU_FTEMP_MINVAL)*HUNDRED_FIVE_PERCENT)


#define EGT_OUTPUT1(fConvertedValue) {\
				if(EGT_VALUE1 >=-55 && EGT_VALUE1 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EGT_VALUE1, 1) + IT_SIPU_C2_0 * pow(EGT_VALUE1, 2) + IT_SIPU_C3_0 *pow(EGT_VALUE1 ,3) + IT_SIPU_C4_0 * pow(EGT_VALUE1 , 4) + IT_SIPU_C5_0 * pow(EGT_VALUE1 , 5) + IT_SIPU_C6_0 * pow(EGT_VALUE1 , 6) + IT_SIPU_C7_0 * pow(EGT_VALUE1 , 7) + IT_SIPU_C8_0 * pow(EGT_VALUE1 ,8) + IT_SIPU_C9_0 * pow(EGT_VALUE1, 9);\
				}\
				else if(EGT_VALUE1 >0 && EGT_VALUE1<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EGT_VALUE1 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE1 , 2) + IT_SIPU_C3_500 * pow(EGT_VALUE1, 3) + IT_SIPU_C4_500 * pow(EGT_VALUE1, 4) + IT_SIPU_C5_500 * pow(EGT_VALUE1, 5) + IT_SIPU_C6_500 * pow(EGT_VALUE1, 6) + IT_SIPU_C7_500 * pow(EGT_VALUE1, 7) + IT_SIPU_C8_500 * pow(EGT_VALUE1,8) + IT_SIPU_C9_500 * pow(EGT_VALUE1, 9);\
				}\
				else if(EGT_VALUE1>500 && EGT_VALUE1<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EGT_VALUE1 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE1 , 2) + IT_SIPU_C3_1000 * pow(EGT_VALUE1 , 3) + IT_SIPU_C4_1000 * pow(EGT_VALUE1,4) + IT_SIPU_C5_1000 * pow(EGT_VALUE1, 5) + IT_SIPU_C6_500 * pow(EGT_VALUE1, 6) + IT_SIPU_C7_1000 * pow(EGT_VALUE1, 7) + IT_SIPU_C8_1000 * pow(EGT_VALUE1,8) + IT_SIPU_C9_1000 * pow(EGT_VALUE1 , 9);\
				}\
			}\
						

#define EGT_OUTPUT2(fConvertedValue)		{\
					float fConvertedValue=0.0;\
					if(EGT_VALUE2 >=-55 && EGT_VALUE2 <=0)\
					{\
						fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EGT_VALUE2 , 1) + IT_SIPU_C2_0 * pow(EGT_VALUE2 , 2) + IT_SIPU_C3_0 *pow(EGT_VALUE2 ,3) + IT_SIPU_C4_0 * pow(EGT_VALUE2 , 4) + IT_SIPU_C5_0 * pow(EGT_VALUE2 , 5) + IT_SIPU_C6_0 * pow(EGT_VALUE2 , 6) + IT_SIPU_C7_0 * pow(EGT_VALUE2 , 7) + IT_SIPU_C8_0 * pow(EGT_VALUE2 ,8) + IT_SIPU_C9_0 * pow(EGT_VALUE2, 9);\
					}\
					else if(EGT_VALUE2 >0 && EGT_VALUE2<=500)\
					{\
						fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EGT_VALUE2 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE2 , 2) + IT_SIPU_C3_500 * pow(EGT_VALUE2 , 3) + IT_SIPU_C4_500 * pow(EGT_VALUE2 , 4) + IT_SIPU_C5_500 * pow(EGT_VALUE2 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE2 , 6) + IT_SIPU_C7_500 * pow(EGT_VALUE2 , 7) + IT_SIPU_C8_500 * pow(EGT_VALUE2 ,8) + IT_SIPU_C9_500 * pow(EGT_VALUE2, 9);\
					}\
					else if(EGT_VALUE2>500 && EGT_VALUE2<=1000)\
					{\
						fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EGT_VALUE2 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE2 , 2) + IT_SIPU_C3_1000 * pow(EGT_VALUE2 , 3) + IT_SIPU_C4_1000 * pow(EGT_VALUE2 ,4) + IT_SIPU_C5_1000 * pow(EGT_VALUE2 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE2 , 6) + IT_SIPU_C7_1000 * pow(EGT_VALUE2 , 7) + IT_SIPU_C8_1000 * pow(EGT_VALUE2 ,8) + IT_SIPU_C9_1000 * pow(EGT_VALUE2 , 9);\
					}\
				}

#define EGT_OUTPUT3(fConvertedValue)		{\
					float fConvertedValue=0.0;\
				if(EGT_VALUE3 >=-55 && EGT_VALUE3 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EGT_VALUE3 , 1) + IT_SIPU_C2_0 * pow(EGT_VALUE3 , 2) + IT_SIPU_C3_0 *pow(EGT_VALUE3 ,3) + IT_SIPU_C4_0 * pow(EGT_VALUE3 , 4) + IT_SIPU_C5_0 * pow(EGT_VALUE3 , 5) + IT_SIPU_C6_0 * pow(EGT_VALUE3 , 6) + IT_SIPU_C7_0 * pow(EGT_VALUE3 , 7) + IT_SIPU_C8_0 * pow(EGT_VALUE3 ,8) + IT_SIPU_C9_0 * pow(EGT_VALUE3, 9);\
				}\
				else if(EGT_VALUE3 >0 && EGT_VALUE3<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EGT_VALUE3 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE3 , 2) + IT_SIPU_C3_500 * pow(EGT_VALUE3 , 3) + IT_SIPU_C4_500 * pow(EGT_VALUE3 , 4) + IT_SIPU_C5_500 * pow(EGT_VALUE3 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE3 , 6) + IT_SIPU_C7_500 * pow(EGT_VALUE3 , 7) + IT_SIPU_C8_500 * pow(EGT_VALUE3 ,8) + IT_SIPU_C9_500 * pow(EGT_VALUE3, 9);\
				}\
				else if(EGT_VALUE3>500 && EGT_VALUE3<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EGT_VALUE3 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE3 , 2) + IT_SIPU_C3_1000 * pow(EGT_VALUE3 , 3) + IT_SIPU_C4_1000 * pow(EGT_VALUE3 ,4) + IT_SIPU_C5_1000 * pow(EGT_VALUE3 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE3 , 6) + IT_SIPU_C7_1000 * pow(EGT_VALUE3 , 7) + IT_SIPU_C8_1000 * pow(EGT_VALUE3 ,8) + IT_SIPU_C9_1000 * pow(EGT_VALUE3 , 9);\
				}\
			}

#define EGT_OUTPUT4(fConvertedValue)		{\
				float fConvertedValue=0.0;\
				if(EGT_VALUE4 >=-55 && EGT_VALUE4 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EGT_VALUE4 , 1) + IT_SIPU_C2_0 * pow(EGT_VALUE4 , 2) + IT_SIPU_C3_0 *pow(EGT_VALUE4 ,3) + IT_SIPU_C4_0 * pow(EGT_VALUE4 , 4) + IT_SIPU_C5_0 * pow(EGT_VALUE4 , 5) + IT_SIPU_C6_0 * pow(EGT_VALUE4 , 6) + IT_SIPU_C7_0 * pow(EGT_VALUE4 , 7) + IT_SIPU_C8_0 * pow(EGT_VALUE4 ,8) + IT_SIPU_C9_0 * pow(EGT_VALUE4, 9);\
				}\
				else if(EGT_VALUE4 >0 && EGT_VALUE4<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EGT_VALUE4 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE4 , 2) + IT_SIPU_C3_500 * pow(EGT_VALUE4 , 3) + IT_SIPU_C4_500 * pow(EGT_VALUE4 , 4) + IT_SIPU_C5_500 * pow(EGT_VALUE4 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE4 , 6) + IT_SIPU_C7_500 * pow(EGT_VALUE4 , 7) + IT_SIPU_C8_500 * pow(EGT_VALUE4 ,8) + IT_SIPU_C9_500 * pow(EGT_VALUE4, 9);\
				}\
				else if(EGT_VALUE4>500 && EGT_VALUE4<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EGT_VALUE4 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE4 , 2) + IT_SIPU_C3_1000 * pow(EGT_VALUE4 , 3) + IT_SIPU_C4_1000 * pow(EGT_VALUE4 ,4) + IT_SIPU_C5_1000 * pow(EGT_VALUE4 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE4 , 6) + IT_SIPU_C7_1000 * pow(EGT_VALUE4 , 7) + IT_SIPU_C8_1000 * pow(EGT_VALUE4 ,8) + IT_SIPU_C9_1000 * pow(EGT_VALUE4 , 9);\
				}\
			}

#define EGT_OUTPUT5(fConvertedValue)		{\
				float fConvertedValue=0.0;\
				if(EGT_VALUE5 >=-55 && EGT_VALUE5 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EGT_VALUE5 , 1) + IT_SIPU_C2_0 * pow(EGT_VALUE5 , 2) + IT_SIPU_C3_0 *pow(EGT_VALUE5 ,3) + IT_SIPU_C4_0 * pow(EGT_VALUE5 , 4) + IT_SIPU_C5_0 * pow(EGT_VALUE5 , 5) + IT_SIPU_C6_0 * pow(EGT_VALUE5 , 6) + IT_SIPU_C7_0 * pow(EGT_VALUE5 , 7) + IT_SIPU_C8_0 * pow(EGT_VALUE5 ,8) + IT_SIPU_C9_0 * pow(EGT_VALUE5, 9);\
				}\
				else if(EGT_VALUE5 >0 && EGT_VALUE5<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EGT_VALUE5 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE5 , 2) + IT_SIPU_C3_500 * pow(EGT_VALUE5 , 3) + IT_SIPU_C4_500 * pow(EGT_VALUE5 , 4) + IT_SIPU_C5_500 * pow(EGT_VALUE5 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE5 , 6) + IT_SIPU_C7_500 * pow(EGT_VALUE5 , 7) + IT_SIPU_C8_500 * pow(EGT_VALUE5 ,8) + IT_SIPU_C9_500 * pow(EGT_VALUE5, 9);\
				}\
				else if(EGT_VALUE5>500 && EGT_VALUE5<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EGT_VALUE5 , 1) + IT_SIPU_C2_500 * pow(EGT_VALUE5 , 2) + IT_SIPU_C3_1000 * pow(EGT_VALUE5 , 3) + IT_SIPU_C4_1000 * pow(EGT_VALUE5 ,4) + IT_SIPU_C5_1000 * pow(EGT_VALUE5 , 5) + IT_SIPU_C6_500 * pow(EGT_VALUE5 , 6) + IT_SIPU_C7_1000 * pow(EGT_VALUE5 , 7) + IT_SIPU_C8_1000 * pow(EGT_VALUE5 ,8) + IT_SIPU_C9_1000 * pow(EGT_VALUE5 , 9);\
				}\
			}

#define EGTEEU_OUTPUT1(fConvertedValue)		{\
				float fConvertedValue=0.0;\
				if(EEU_VALUE1 >=-55 && EEU_VALUE1 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EEU_VALUE1 , 1) + IT_SIPU_C2_0 * pow(EEU_VALUE1 , 2) + IT_SIPU_C3_0 *pow(EEU_VALUE1 ,3) + IT_SIPU_C4_0 * pow(EEU_VALUE1 , 4) + IT_SIPU_C5_0 * pow(EEU_VALUE1 , 5) + IT_SIPU_C6_0 * pow(EEU_VALUE1 , 6) + IT_SIPU_C7_0 * pow(EEU_VALUE1 , 7) + IT_SIPU_C8_0 * pow(EEU_VALUE1 ,8) + IT_SIPU_C9_0 * pow(EEU_VALUE1, 9);\
				}\
				else if(EEU_VALUE1 >0 && EEU_VALUE1<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EEU_VALUE1 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE1 , 2) + IT_SIPU_C3_500 * pow(EEU_VALUE1 , 3) + IT_SIPU_C4_500 * pow(EEU_VALUE1 , 4) + IT_SIPU_C5_500 * pow(EEU_VALUE1 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE1 , 6) + IT_SIPU_C7_500 * pow(EEU_VALUE1 , 7) + IT_SIPU_C8_500 * pow(EEU_VALUE1 ,8) + IT_SIPU_C9_500 * pow(EEU_VALUE1, 9);\
				}\
				else if(EEU_VALUE1>500 && EEU_VALUE1<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EEU_VALUE1 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE1 , 2) + IT_SIPU_C3_1000 * pow(EEU_VALUE1 , 3) + IT_SIPU_C4_1000 * pow(EEU_VALUE1 ,4) + IT_SIPU_C5_1000 * pow(EEU_VALUE1 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE1 , 6) + IT_SIPU_C7_1000 * pow(EEU_VALUE1 , 7) + IT_SIPU_C8_1000 * pow(EEU_VALUE1 ,8) + IT_SIPU_C9_1000 * pow(EEU_VALUE1 , 9);\
				}\
			}

#define EGTEEU_OUTPUT2(fConvertedValue)		{\
				float fConvertedValue=0.0;\
				if(EEU_VALUE2 >=-55 && EEU_VALUE2 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EEU_VALUE2 , 1) + IT_SIPU_C2_0 * pow(EEU_VALUE2 , 2) + IT_SIPU_C3_0 *pow(EEU_VALUE2 ,3) + IT_SIPU_C4_0 * pow(EEU_VALUE2 , 4) + IT_SIPU_C5_0 * pow(EEU_VALUE2 , 5) + IT_SIPU_C6_0 * pow(EEU_VALUE2 , 6) + IT_SIPU_C7_0 * pow(EEU_VALUE2 , 7) + IT_SIPU_C8_0 * pow(EEU_VALUE2 ,8) + IT_SIPU_C9_0 * pow(EEU_VALUE2, 9);\
				}\
				else if(EEU_VALUE2 >0 && EEU_VALUE2<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EEU_VALUE2 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE2 , 2) + IT_SIPU_C3_500 * pow(EEU_VALUE2 , 3) + IT_SIPU_C4_500 * pow(EEU_VALUE2 , 4) + IT_SIPU_C5_500 * pow(EEU_VALUE2 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE2 , 6) + IT_SIPU_C7_500 * pow(EEU_VALUE2 , 7) + IT_SIPU_C8_500 * pow(EEU_VALUE2 ,8) + IT_SIPU_C9_500 * pow(EEU_VALUE2, 9);\
				}\
				else if(EEU_VALUE2>500 && EEU_VALUE2<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EEU_VALUE2 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE2 , 2) + IT_SIPU_C3_1000 * pow(EEU_VALUE2 , 3) + IT_SIPU_C4_1000 * pow(EEU_VALUE2 ,4) + IT_SIPU_C5_1000 * pow(EEU_VALUE2 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE2 , 6) + IT_SIPU_C7_1000 * pow(EEU_VALUE2 , 7) + IT_SIPU_C8_1000 * pow(EEU_VALUE2 ,8) + IT_SIPU_C9_1000 * pow(EEU_VALUE2 , 9);\
				}\
			}

#define EGTEEU_OUTPUT3(fConvertedValue)		{\
				float fConvertedValue=0.0;\
				if(EEU_VALUE3 >=-55 && EEU_VALUE3 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EEU_VALUE3 , 1) + IT_SIPU_C2_0 * pow(EEU_VALUE3 , 2) + IT_SIPU_C3_0 *pow(EEU_VALUE3 ,3) + IT_SIPU_C4_0 * pow(EEU_VALUE3 , 4) + IT_SIPU_C5_0 * pow(EEU_VALUE3 , 5) + IT_SIPU_C6_0 * pow(EEU_VALUE3 , 6) + IT_SIPU_C7_0 * pow(EEU_VALUE3 , 7) + IT_SIPU_C8_0 * pow(EEU_VALUE3 ,8) + IT_SIPU_C9_0 * pow(EEU_VALUE3, 9);\
				}\
				else if(EEU_VALUE3 >0 && EEU_VALUE3<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EEU_VALUE3 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE3 , 2) + IT_SIPU_C3_500 * pow(EEU_VALUE3 , 3) + IT_SIPU_C4_500 * pow(EEU_VALUE3 , 4) + IT_SIPU_C5_500 * pow(EEU_VALUE3 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE3 , 6) + IT_SIPU_C7_500 * pow(EEU_VALUE3 , 7) + IT_SIPU_C8_500 * pow(EEU_VALUE3 ,8) + IT_SIPU_C9_500 * pow(EEU_VALUE3, 9);\
				}\
				else if(EEU_VALUE3>500 && EEU_VALUE3<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EEU_VALUE3 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE3 , 2) + IT_SIPU_C3_1000 * pow(EEU_VALUE3 , 3) + IT_SIPU_C4_1000 * pow(EEU_VALUE3 ,4) + IT_SIPU_C5_1000 * pow(EEU_VALUE3 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE3 , 6) + IT_SIPU_C7_1000 * pow(EEU_VALUE3 , 7) + IT_SIPU_C8_1000 * pow(EEU_VALUE3 ,8) + IT_SIPU_C9_1000 * pow(EEU_VALUE3 , 9);\
				}\
			}

#define EGTEEU_OUTPUT4(fConvertedValue)		{\
				float fConvertedValue=0.0;\
				if(EEU_VALUE4 >=-55 && EEU_VALUE4 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EEU_VALUE4 , 1) + IT_SIPU_C2_0 * pow(EEU_VALUE4 , 2) + IT_SIPU_C3_0 *pow(EEU_VALUE4 ,3) + IT_SIPU_C4_0 * pow(EEU_VALUE4 , 4) + IT_SIPU_C5_0 * pow(EEU_VALUE4 , 5) + IT_SIPU_C6_0 * pow(EEU_VALUE4 , 6) + IT_SIPU_C7_0 * pow(EEU_VALUE4 , 7) + IT_SIPU_C8_0 * pow(EEU_VALUE4 ,8) + IT_SIPU_C9_0 * pow(EEU_VALUE4, 9);\
				}\
				else if(EEU_VALUE4 >0 && EEU_VALUE4<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EEU_VALUE4 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE4 , 2) + IT_SIPU_C3_500 * pow(EEU_VALUE4 , 3) + IT_SIPU_C4_500 * pow(EEU_VALUE4 , 4) + IT_SIPU_C5_500 * pow(EEU_VALUE4 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE4 , 6) + IT_SIPU_C7_500 * pow(EEU_VALUE4 , 7) + IT_SIPU_C8_500 * pow(EEU_VALUE4 ,8) + IT_SIPU_C9_500 * pow(EEU_VALUE4, 9);\
				}\
				else if(EEU_VALUE4>500 && EEU_VALUE4<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EEU_VALUE4 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE4 , 2) + IT_SIPU_C3_1000 * pow(EEU_VALUE4 , 3) + IT_SIPU_C4_1000 * pow(EEU_VALUE4 ,4) + IT_SIPU_C5_1000 * pow(EEU_VALUE4 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE4 , 6) + IT_SIPU_C7_1000 * pow(EEU_VALUE4 , 7) + IT_SIPU_C8_1000 * pow(EEU_VALUE4 ,8) + IT_SIPU_C9_1000 * pow(EEU_VALUE4 , 9);\
				}\
			}

#define EGTEEU_OUTPUT5(fConvertedValue)		{\
				float fConvertedValue=0.0;\
				if(EEU_VALUE5 >=-55 && EEU_VALUE5 <=0)\
				{\
					fConvertedValue=IT_SIPU_C0_0 + IT_SIPU_C1_0 * pow(EEU_VALUE5 , 1) + IT_SIPU_C2_0 * pow(EEU_VALUE5 , 2) + IT_SIPU_C3_0 *pow(EEU_VALUE5 ,3) + IT_SIPU_C4_0 * pow(EEU_VALUE5 , 4) + IT_SIPU_C5_0 * pow(EEU_VALUE5 , 5) + IT_SIPU_C6_0 * pow(EEU_VALUE5 , 6) + IT_SIPU_C7_0 * pow(EEU_VALUE5 , 7) + IT_SIPU_C8_0 * pow(EEU_VALUE5 ,8) + IT_SIPU_C9_0 * pow(EEU_VALUE5, 9);\
				}\
				else if(EEU_VALUE5 >0 && EEU_VALUE5<=500)\
				{\
					fConvertedValue=IT_SIPU_C0_500 + IT_SIPU_C1_500 * pow(EEU_VALUE5 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE5 , 2) + IT_SIPU_C3_500 * pow(EEU_VALUE5 , 3) + IT_SIPU_C4_500 * pow(EEU_VALUE5 , 4) + IT_SIPU_C5_500 * pow(EEU_VALUE5 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE5 , 6) + IT_SIPU_C7_500 * pow(EEU_VALUE5 , 7) + IT_SIPU_C8_500 * pow(EEU_VALUE5 ,8) + IT_SIPU_C9_500 * pow(EEU_VALUE5, 9);\
				}\
				else if(EEU_VALUE5>500 && EEU_VALUE5<=1000)\
				{\
					fConvertedValue=IT_SIPU_C0_1000 + IT_SIPU_C1_1000 * pow(EEU_VALUE5 , 1) + IT_SIPU_C2_500 * pow(EEU_VALUE5 , 2) + IT_SIPU_C3_1000 * pow(EEU_VALUE5 , 3) + IT_SIPU_C4_1000 * pow(EEU_VALUE5 ,4) + IT_SIPU_C5_1000 * pow(EEU_VALUE5 , 5) + IT_SIPU_C6_500 * pow(EEU_VALUE5 , 6) + IT_SIPU_C7_1000 * pow(EEU_VALUE5 , 7) + IT_SIPU_C8_1000 * pow(EEU_VALUE5 ,8) + IT_SIPU_C9_1000 * pow(EEU_VALUE5 , 9);\
				}\
			}


#define N1FREQ_OUTPUT1		((IT_SIPU_N1_A*N1FREQ_VALUE1) - IT_SIPU_N1_C)
#define N1FREQ_OUTPUT2		((IT_SIPU_N1_A*N1FREQ_VALUE2) - IT_SIPU_N1_C)
#define N1FREQ_OUTPUT3		((IT_SIPU_N1_A*N1FREQ_VALUE3) - IT_SIPU_N1_C)
#define N1FREQ_OUTPUT4		((IT_SIPU_N1_A*N1FREQ_VALUE4) - IT_SIPU_N1_C)
#define N1FREQ_OUTPUT5		((IT_SIPU_N1_A*N1FREQ_VALUE5) - IT_SIPU_N1_C)

#define N2FREQ_OUTPUT1		((IT_SIPU_N2_A*N2FREQ_VALUE1)-IT_SIPU_N2_C)	
#define N2FREQ_OUTPUT2		((IT_SIPU_N2_A*N2FREQ_VALUE2)-IT_SIPU_N2_C)	
#define N2FREQ_OUTPUT3		((IT_SIPU_N2_A*N2FREQ_VALUE3)-IT_SIPU_N2_C)	
#define N2FREQ_OUTPUT4		((IT_SIPU_N2_A*N2FREQ_VALUE4)-IT_SIPU_N2_C)	
#define N2FREQ_OUTPUT5		((IT_SIPU_N2_A*N2FREQ_VALUE5)-IT_SIPU_N2_C)	

#define N1FREQEEU_OUTPUT1		((IT_SIPU_N1_A*EEU_VALUE1) - IT_SIPU_N1_C)
#define N1FREQEEU_OUTPUT2		((IT_SIPU_N1_A*EEU_VALUE2) - IT_SIPU_N1_C)
#define N1FREQEEU_OUTPUT3		((IT_SIPU_N1_A*EEU_VALUE3) - IT_SIPU_N1_C)
#define N1FREQEEU_OUTPUT4		((IT_SIPU_N1_A*EEU_VALUE4) - IT_SIPU_N1_C)
#define N1FREQEEU_OUTPUT5		((IT_SIPU_N1_A*EEU_VALUE5) - IT_SIPU_N1_C)

#define N2FREQEEU_OUTPUT1		((IT_SIPU_N2_A*EEU_VALUE1) - IT_SIPU_N2_C)
#define N2FREQEEU_OUTPUT2		((IT_SIPU_N2_A*EEU_VALUE2) - IT_SIPU_N2_C)
#define N2FREQEEU_OUTPUT3		((IT_SIPU_N2_A*EEU_VALUE3) - IT_SIPU_N2_C)
#define N2FREQEEU_OUTPUT4		((IT_SIPU_N2_A*EEU_VALUE4) - IT_SIPU_N2_C)
#define N2FREQEEU_OUTPUT5		((IT_SIPU_N2_A*EEU_VALUE5) - IT_SIPU_N2_C)

#define FUSELAGE_OUTPUT1		0
#define FUSELAGE_OUTPUT2		582.0164
#define FUSELAGE_OUTPUT3		213.41348
#define FUSELAGE_OUTPUT4		7.8466
#define FUSELAGE_OUTPUT5		0

#define MHYDPRES_OUTPUT1		(MHYDPRES_VALUE1*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define MHYDPRES_OUTPUT2		(MHYDPRES_VALUE2*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define MHYDPRES_OUTPUT3		(MHYDPRES_VALUE3*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define MHYDPRES_OUTPUT4		(MHYDPRES_VALUE4*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define MHYDPRES_OUTPUT5		(MHYDPRES_VALUE5*IT_SIPU_HYD_A)-IT_SIPU_HYD_C

#define EHYDPRES_OUTPUT1		(EHYDPRES_VALUE1*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define EHYDPRES_OUTPUT2		(EHYDPRES_VALUE2*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define EHYDPRES_OUTPUT3		(EHYDPRES_VALUE3*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define EHYDPRES_OUTPUT4		(EHYDPRES_VALUE4*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
#define EHYDPRES_OUTPUT5		(EHYDPRES_VALUE5*IT_SIPU_HYD_A)-IT_SIPU_HYD_C
								
#define LHBRKPRES_OUTPUT1		((LHBRKPRES_VALUE1*IT_SIPU_HYD_A)-IT_SIPU_HYD_C)
#define LHBRKPRES_OUTPUT2		((LHBRKPRES_VALUE2*IT_SIPU_HYD_A)-IT_SIPU_HYD_C)
#define LHBRKPRES_OUTPUT3		((LHBRKPRES_VALUE3*IT_SIPU_HYD_A)-IT_SIPU_HYD_C)
#define LHBRKPRES_OUTPUT4		((LHBRKPRES_VALUE4*IT_SIPU_HYD_A)-IT_SIPU_HYD_C)
#define LHBRKPRES_OUTPUT5		((LHBRKPRES_VALUE5*IT_SIPU_HYD_A)-IT_SIPU_HYD_C)
								
#define RHBRKPRES_OUTPUT1		(RHBRKPRES_VALUE1*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define RHBRKPRES_OUTPUT2		(RHBRKPRES_VALUE2*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define RHBRKPRES_OUTPUT3		(RHBRKPRES_VALUE3*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define RHBRKPRES_OUTPUT4		(RHBRKPRES_VALUE4*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define RHBRKPRES_OUTPUT5		(RHBRKPRES_VALUE5*IT_SIPU_BRK_A)-IT_SIPU_BRK_C

#define MSUPBRKPRES_OUTPUT1		(MSUPBRKPRES_VALUE1*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define MSUPBRKPRES_OUTPUT2		(MSUPBRKPRES_VALUE2*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define MSUPBRKPRES_OUTPUT3		(MSUPBRKPRES_VALUE3*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define MSUPBRKPRES_OUTPUT4		(MSUPBRKPRES_VALUE4*IT_SIPU_BRK_A)-IT_SIPU_BRK_C
#define MSUPBRKPRES_OUTPUT5		(MSUPBRKPRES_VALUE5*IT_SIPU_BRK_A)-IT_SIPU_BRK_C

#define TPTRIMPOS_OUTPUT1		(TPTRIMPOS_VALUE1*IT_SIPU_TAIL_A)-IT_SIPU_TAIL_C
#define TPTRIMPOS_OUTPUT2		(TPTRIMPOS_VALUE2*IT_SIPU_TAIL_A)-IT_SIPU_TAIL_C
#define TPTRIMPOS_OUTPUT3		(TPTRIMPOS_VALUE3*IT_SIPU_TAIL_A)-IT_SIPU_TAIL_C
#define TPTRIMPOS_OUTPUT4		(TPTRIMPOS_VALUE4*IT_SIPU_TAIL_A)-IT_SIPU_TAIL_C
#define TPTRIMPOS_OUTPUT5		(TPTRIMPOS_VALUE5*IT_SIPU_TAIL_A)-IT_SIPU_TAIL_C

#define AILTRIMPOS_OUTPUT1		(AILTRIMPOS_VALUE1*IT_SIPU_AIL_A)-IT_SIPU_AIL_C
#define AILTRIMPOS_OUTPUT2		(AILTRIMPOS_VALUE2*IT_SIPU_AIL_A)-IT_SIPU_AIL_C
#define AILTRIMPOS_OUTPUT3		(AILTRIMPOS_VALUE3*IT_SIPU_AIL_A)-IT_SIPU_AIL_C
#define AILTRIMPOS_OUTPUT4		(AILTRIMPOS_VALUE4*IT_SIPU_AIL_A)-IT_SIPU_AIL_C
#define AILTRIMPOS_OUTPUT5		(AILTRIMPOS_VALUE5*IT_SIPU_AIL_A)-IT_SIPU_AIL_C

#define RUDTRIMPOS_OUTPUT1		(RUDTRIMPOS_VALUE1*IT_SIPU_RUD_A)-IT_SIPU_RUD_C
#define RUDTRIMPOS_OUTPUT2		(RUDTRIMPOS_VALUE2*IT_SIPU_RUD_A)-IT_SIPU_RUD_C
#define RUDTRIMPOS_OUTPUT3		(RUDTRIMPOS_VALUE3*IT_SIPU_RUD_A)-IT_SIPU_RUD_C
#define RUDTRIMPOS_OUTPUT4		(RUDTRIMPOS_VALUE4*IT_SIPU_RUD_A)-IT_SIPU_RUD_C
#define RUDTRIMPOS_OUTPUT5		(RUDTRIMPOS_VALUE5*IT_SIPU_RUD_A)-IT_SIPU_RUD_C
			
#define FLAPPOS_OUTPUT1		IT_SIPU_FLAP_A * (FLAPPOS_VALUE1 - IT_SIPU_FLAP_C)
#define FLAPPOS_OUTPUT2		IT_SIPU_FLAP_A * (FLAPPOS_VALUE2 - IT_SIPU_FLAP_C)
#define FLAPPOS_OUTPUT3		IT_SIPU_FLAP_A * (FLAPPOS_VALUE3 - IT_SIPU_FLAP_C)
#define FLAPPOS_OUTPUT4		IT_SIPU_FLAP_A * (FLAPPOS_VALUE4 - IT_SIPU_FLAP_C)
#define FLAPPOS_OUTPUT5		IT_SIPU_FLAP_A * (FLAPPOS_VALUE5 - IT_SIPU_FLAP_C)

#define CABPRES_OUTPUT1		240*CABPRES_VALUE1
#define CABPRES_OUTPUT2		240*CABPRES_VALUE2
#define CABPRES_OUTPUT3		240*CABPRES_VALUE3
#define CABPRES_OUTPUT4		240*CABPRES_VALUE4
#define CABPRES_OUTPUT5		240*CABPRES_VALUE5
											
/* Channel Numbers for SIPU Auto Mode Excitation */

#define IT_SIPU_HYDPRES_MAIN 1
#define IT_SIPU_HYDPRES_EMER 2
#define IT_SIPU_LH_BRK_PRES 3
#define IT_SIPU_RH_BRK_PRES 4
#define IT_SIPU_MAIN_BRK_PRES 5
#define IT_SIPU_CABIN_DP 6
#define IT_SIPU_RH_WT_CONTENT 7
#define IT_SIPU_LH_WT_CONTENT 12
#define IT_SIPU_FUSELAGE 8
#define IT_SIPU_DETOTALIZER 11
#define IT_SIPU_1mA_DRIVE 8
#define IT_SIPU_TAILPLANE 13
#define IT_SIPU_FLAP_POS 14
#define IT_SIPU_AIL 15
#define IT_SIPU_RUDDER 16
#define IT_SIPU_AIRBRK 10



#endif